- concepts_list:
  - instance_prompt: photo of orpi button
    class_prompt: photo of an button
    instance_data_dir: /home/team2/stable_diffusion/data/kennurkaya/orpi
    class_data_dir: /content/data/button
  - instance_prompt: photo of brunnz dress
    class_prompt: photo of a dress
    instance_data_dir: /home/team2/stable_diffusion/data/kennurkaya/brunnz
    class_data_dir: /content/data/dress
  - instance_prompt: photo of picol sweatshirt
    class_prompt: photo of a sweatshirt
    instance_data_dir: /home/team2/stable_diffusion/data/kennurkaya/picol
    class_data_dir: /content/data/sweatshirt
  - instance_prompt: photo of munique paint
    class_prompt: photo of a paint
    instance_data_dir: /home/team2/stable_diffusion/data/kennurkaya/munique
    class_data_dir: /content/data/paint
  - instance_prompt: photo of yummz pattern
    class_prompt: photo of a pattern
    instance_data_dir: /home/team2/stable_diffusion/data/kennurkaya/yummz
    class_data_dir: /content/data/pattern
  weights_path: /home/team2/stable_diffusion/weights/kennurkaya/800
- concepts_list:
  - instance_prompt: photo of bejflow dress
    class_prompt: photo of an dress
    instance_data_dir: /home/team2/stable_diffusion/data/kennurbaya/bejflow
    class_data_dir: /content/data/button
  - instance_prompt: photo of bluski skirt
    class_prompt: photo of a skirt
    instance_data_dir: /home/team2/stable_diffusion/data/kennurbaya/bluski
    class_data_dir: /content/data/dress
  - instance_prompt: photo of coleo shape
    class_prompt: photo of a shape
    instance_data_dir: /home/team2/stable_diffusion/data/kennurbaya/coleo
    class_data_dir: /content/data/sweatshirt
  - instance_prompt: photo of munique painting
    class_prompt: photo of a painting
    instance_data_dir: /home/team2/stable_diffusion/data/kennurbaya/munique
    class_data_dir: /content/data/paint
  - instance_prompt: photo of yummz pattern
    class_prompt: photo of a pattern
    instance_data_dir: /home/team2/stable_diffusion/data/kennurbaya/yummz
    class_data_dir: /content/data/pattern
  - instance_prompt: photo of crocod boots
    class_prompt: photo of a boots
    instance_data_dir: /home/team2/stable_diffusion/data/kennurbaya/crocod
    class_data_dir: /content/data/pattern
  - instance_prompt: photo of cutenose pillow
    class_prompt: photo of a pillow
    instance_data_dir: /home/team2/stable_diffusion/data/kennurbaya/cutenose
    class_data_dir: /content/data/pattern 
  - instance_prompt: photo of fabwom woman
    class_prompt: photo of a woman
    instance_data_dir: /home/team2/stable_diffusion/data/kennurbaya/fabwom
    class_data_dir: /content/data/pattern
  - instance_prompt: photo of flowre necklace
    class_prompt: photo of a necklace
    instance_data_dir: /home/team2/stable_diffusion/data/kennurbaya/flowre
    class_data_dir: /content/data/pattern
  - instance_prompt: photo of guzel tshirt
    class_prompt: photo of a tshirt
    instance_data_dir: /home/team2/stable_diffusion/data/kennurbaya/guzel
    class_data_dir: /content/data/pattern
  - instance_prompt: photo of lalala sweatshirt
    class_prompt: photo of a sweatshirt
    instance_data_dir: /home/team2/stable_diffusion/data/kennurbaya/sweatshirt
    class_data_dir: /content/data/pattern
  - instance_prompt: photo of lovelz pants
    class_prompt: photo of a pants
    instance_data_dir: /home/team2/stable_diffusion/data/kennurbaya/lovelz
    class_data_dir: /content/data/pattern
  - instance_prompt: photo of mavibe dress
    class_prompt: photo of a dress
    instance_data_dir: /home/team2/stable_diffusion/data/kennurbaya/mavibe
    class_data_dir: /content/data/pattern
  - instance_prompt: photo of meltin painting
    class_prompt: photo of an painting
    instance_data_dir: /home/team2/stable_diffusion/data/kennurbaya/meltin
    class_data_dir: /content/data/button
  - instance_prompt: photo of moop bag
    class_prompt: photo of a bag
    instance_data_dir: /home/team2/stable_diffusion/data/kennurbaya/moop
    class_data_dir: /content/data/dress
  - instance_prompt: photo of mymon coat
    class_prompt: photo of a coat
    instance_data_dir: /home/team2/stable_diffusion/data/kennurbaya/mymon
    class_data_dir: /content/data/sweatshirt
  - instance_prompt: photo of mystcfor view
    class_prompt: photo of a view
    instance_data_dir: /home/team2/stable_diffusion/data/kennurbaya/mystcfor
    class_data_dir: /content/data/paint
  - instance_prompt: photo of oldgold figure
    class_prompt: photo of a figure
    instance_data_dir: /home/team2/stable_diffusion/data/kennurbaya/oldgold
    class_data_dir: /content/data/pattern
  - instance_prompt: photo of onne design
    class_prompt: photo of a design
    instance_data_dir: /home/team2/stable_diffusion/data/kennurbaya/onne
    class_data_dir: /content/data/pattern
  - instance_prompt: photo of orpi button
    class_prompt: photo of a button
    instance_data_dir: /home/team2/stable_diffusion/data/kennurbaya/orpi
    class_data_dir: /content/data/pattern 
  - instance_prompt: photo of picol sweatshirt
    class_prompt: photo of a sweatshirt
    instance_data_dir: /home/team2/stable_diffusion/data/kennurbaya/picol
    class_data_dir: /content/data/pattern
  - instance_prompt: photo of rhot clothing
    class_prompt: photo of a clothing
    instance_data_dir: /home/team2/stable_diffusion/data/kennurbaya/rhot
    class_data_dir: /content/data/pattern
  - instance_prompt: photo of sallz cartoon
    class_prompt: photo of a cartoon
    instance_data_dir: /home/team2/stable_diffusion/data/kennurbaya/sallz
    class_data_dir: /content/data/pattern
  - instance_prompt: photo of smvibe bikini
    class_prompt: photo of a bikini
    instance_data_dir: /home/team2/stable_diffusion/data/kennurbaya/smvibe
    class_data_dir: /content/data/pattern
  weights_path: /home/team2/stable_diffusion/weights/kennurbaya/800