adam_beta1: 0.9
adam_beta2: 0.999
adam_epsilon: 1.0e-08
adam_weight_decay: 0.01
center_crop: null
class_data_dir: null
class_prompt: null
concepts_list: concepts_list.json
gradient_accumulation_steps: 1
gradient_checkpointing: null
hflip: false
hub_token: null
instance_data_dir: null
instance_prompt: null
learning_rate: 1.0e-06
local_rank: -1
log_interval: 10
logging_dir: logs
lr_scheduler: constant
lr_warmup_steps: 500
max_grad_norm: 1.0
max_train_steps: 200
mixed_precision: fp16
n_save_sample: 4
not_cache_latents: null
num_class_images: 50
num_train_epochs: 1
output_dir: /home/team2/stable_diffusion/weights/testing
pad_tokens: false
pretrained_model_name_or_path: /home/team2/stable_diffusion/weights/demo/400
pretrained_vae_name_or_path: stabilityai/sd-vae-ft-mse
prior_loss_weight: 1.0
push_to_hub: false
read_prompts_from_txts: null
resolution: 512
revision: fp16
sample_batch_size: 4
save_guidance_scale: 7.5
save_infer_steps: 20
save_interval: 1000
save_min_steps: 0
save_sample_negative_prompt: null
save_sample_prompt: photo lur long dress
scale_lr: false
seed: 1337
tokenizer_name: null
train_batch_size: 1
train_text_encoder: true
use_8bit_adam: true
with_prior_preservation: true
